server:
  port: 8080
spring:
  application:
    name: clour-grpc-client
  sleuth:
    sampler:
      probability: 1
    baggage-keys: # 注意，Sleuth 2.0.0 之后，baggage 的 key 必须在这里配置才能生效
      - SessionId
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/