server:
  port: 6100
spring:
  application:
    name: clour-grpc-client
  zipkin:
    base-url: http://zipkin.changhr.com
  sleuth:
    sampler:
      probability: 1
    baggage-keys: # 注意，Sleuth 2.0.0 之后，baggage 的 key 必须在这里配置才能生效
      - SessionId
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.37:8080/eureka/
# 切换到 PLAINTEXT 的连接方式
# https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/README-zh.md#%E6%B5%8B%E8%AF%95%E6%9C%9F%E9%97%B4-ssl-%E7%9A%84%E9%97%AE%E9%A2%98
grpc:
  client:
    cloud-grpc-server:
      negotiationType: PLAINTEXT