#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: false
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://192.168.1.37:8080