#server:
#  port: 6103

#spring:
#  application:
#    name: cloud-apollo-client

#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.1.37:8080/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    tags:
#      application: cloud-apollo-client

#spring:
#  redis:
#    database: 0
#    host: 192.168.1.37
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms

apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://192.168.1.37:18080
