#server:
#  port: 6103

#spring:
#  application:
#    name: cloud-apollo-client
#  redis:
#    database: 0
#    host: redis.changhr.com
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    tags:
#      application: cloud-apollo-client

#service:
#  token:
#    url: http://iot-s-token.senseyun.com

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/

apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://apollo.config.changhr.com
