server:
  port: 6103
spring:
  application:
    name: cloud-apollo-client
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.37:8080/eureka/
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://192.168.1.37:8080